# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-08-26 05:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20170826_0455'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='mrp',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
